force-app/main/default/objects/Adyen_Adapter__mdt/Adyen_Adapter__mdt.object-meta.xml
<CustomObject>
    <label>Adyen Adapter</label>
    <pluralLabel>Adyen Adapters</pluralLabel>
</CustomObject>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Client_Key__c.field-meta.xml
<CustomField>
    <fullName>Client_Key__c</fullName>
    <description>Client key to authenticate requests</description>
    <inlineHelpText>Can be found at the customer area</inlineHelpText>
    <label>Client Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

adyen-appexchange/main/default/objects/Adyen_Adapter__mdt/fields/Endpoint_Api_Version__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Api_Version__c</fullName>
    <defaultValue>&quot;/v68&quot;</defaultValue>
    <description>The Api Version of the Endpoint.. ie. v52</description>
    <inlineHelpText>The Api Version of the Endpoint ie. v52</inlineHelpText>
    <label>Endpoint Api Version</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

adyen-appexchange/force-app/main/default/objects/Adyen_Adapter__mdt/fields/Merchant_Account__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Account__c</fullName>
    <label>Merchant Account</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Payment_Methods_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Payment_Methods_Endpoint__c</fullName>
    <label>Payment Methods Endpoint</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

adyen-appexchange/force-app/main/default/objects/Adyen_Adapter__mdt/fields/Payments_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Payments_Endpoint__c</fullName>
    <label>Payments Endpoint</label>
    <length>64</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

adyen-appexchange/force-app/main/default/objects/Adyen_Adapter__mdt/fields/System_Integrator_Name__c.field-meta.xml
<CustomField>
    <fullName>System_Integrator_Name__c</fullName>
    <label>System Integrator Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

adyen-appexchange/force-app/main/default/classes/AdyenB2BUtils.cls
public with sharing class AdyenB2BUtils {
    public static Adyen_Adapter__mdt retrieveAdyenAdapter(String adyenAdapterName) {
        try {
            return [
                SELECT Merchant_Account__c, Endpoint_Api_Version__c, Payment_Methods_Endpoint__c, Client_Key__c, Payments_Endpoint__c, System_Integrator_Name__c
                FROM Adyen_Adapter__mdt
                WHERE DeveloperName = :adyenAdapterName
                WITH SECURITY_ENFORCED
            ];
        } catch (Exception ex) {
            throw new AuraHandledException('Could not find adyen adapter with name: ' + adyenAdapterName + '. Error: ' + ex.getMessage());
        }
    }

    public static HttpResponse makePostRequest(Adyen_Adapter__mdt adyenAdapter, String endpointFieldName, String body) {
        String compatibleBody = makeAdyenCompatible(body);
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:AdyenCheckout' + buildEndpoint(adyenAdapter, endpointFieldName));
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setBody(compatibleBody);
        HttpResponse response = new Http().send(req);
        if (response.getStatusCode() != 200) {
            throw new AuraHandledException('API returned: ' + response.getStatusCode());
        } else {
            return response;
        }
    }

    private static String buildEndpoint(Adyen_Adapter__mdt adyenAdapter, String endpointFieldName) {
        try {
            return adyenAdapter.Endpoint_Api_Version__c + adyenAdapter.get(endpointFieldName);
        } catch (Exception ex) {
            throw new AuraHandledException('Could not build endpoint with field: ' + endpointFieldName + '. Error: ' + ex.getMessage());
        }

    }

    private static String makeAdyenCompatible(String input) {
        Map<String, String> mapKeyToReplace = new Map<String, String> {
                'currency_x' => 'currency',
                'number_x' => 'number',
                'group_x' => 'group'
        };
        String output = input;
        for (String key : mapKeyToReplace.keySet()) {
            output = output.replace(key, mapKeyToReplace.get(key));
        }
        return output;
    }

    public static Id fetchAdyenGatewayId() {
        return [SELECT Id FROM PaymentGateway WHERE PaymentGatewayName = :AdyenB2BConstants.DEFAULT_PAYMENT_GATEWAY_NAME].Id;
    }

    public static String makeSalesforceCompatible(String adyenPaymentMethodType) {
        String salesForcePayMethodType = AdyenB2BConstants.ADYEN_PAYMENT_TYPE_TO_SF_TYPE.get(adyenPaymentMethodType);
        return String.isNotBlank(salesForcePayMethodType) ? salesForcePayMethodType : adyenPaymentMethodType;
    }

    public static ApplicationInfo getApplicationInfo(String systemIntegratorName) {
        ApplicationInfo applicationInfo = new ApplicationInfo();

        ExternalPlatform externalPlatform = new ExternalPlatform();
        externalPlatform.name = AdyenB2BConstants.EXTERNAL_PLATFORM_NAME_FOR_APP_INFO;
        externalPlatform.integrator = systemIntegratorName;
        applicationInfo.externalPlatform = externalPlatform;

        CommonField merchantApplication = new CommonField();
        merchantApplication.name = AdyenB2BConstants.MERCHANT_APP_NAME_FOR_APP_INFO;
        merchantApplication.version = AdyenB2BConstants.MERCHANT_APP_VERSION_FOR_APP_INFO;
        applicationInfo.merchantApplication = merchantApplication;

        CommonField adyenLibrary = new CommonField();
        adyenLibrary.name = AdyenB2BConstants.ADYEN_LIBRARY_NAME_FOR_APP_INFO;
        adyenLibrary.version = AdyenB2BConstants.ADYEN_LIBRARY_VERSION_FOR_APP_INFO;
        applicationInfo.adyenLibrary = adyenLibrary;

        return applicationInfo;
    }
}