force-app/main/default/objects/Adyen_Adapter__mdt/Adyen_Adapter__mdt.object-meta.xml
<CustomObject>
    <label>Adyen Adapter</label>
    <pluralLabel>Adyen Adapters</pluralLabel>
</CustomObject>

adyen-appexchange/main/default/objects/Adyen_Adapter__mdt/fields/Endpoint_Api_Version__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_Api_Version__c</fullName>
    <defaultValue>&quot;/v68&quot;</defaultValue>
    <description>The Api Version of the Endpoint.. ie. v52</description>
    <inlineHelpText>The Api Version of the Endpoint ie. v52</inlineHelpText>
    <label>Endpoint Api Version</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

adyen-appexchange/force-app/main/default/objects/Adyen_Adapter__mdt/fields/Merchant_Account__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Account__c</fullName>
    <label>Merchant Account</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Adyen_Adapter__mdt/fields/Payment_Methods_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Payment_Methods_Endpoint__c</fullName>
    <label>Payment Methods Endpoint</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

adyen-appexchange/force-app/main/default/classes/AdyenUtils.cls
/**
 * Created by daniloc on 23/11/2023.
 */

public with sharing class AdyenUtils {
    public static Adyen_Adapter__mdt retrieveAdyenAdapter(String adyenAdapterName) {
        try {
            return [
                SELECT Merchant_Account__c, Endpoint_Api_Version__c, Payment_Methods_Endpoint__c
                FROM Adyen_Adapter__mdt
                WHERE DeveloperName = :adyenAdapterName
                WITH SECURITY_ENFORCED
            ];
        } catch (Exception ex) {
            throw new AuraHandledException('Could not find adyen adapter with name: ' + adyenAdapterName + '. Error: ' + ex.getMessage());
        }
    }

    public static List<PaymentMethod> filterOnlyCardPaymentMethod(List<PaymentMethod> paymentMethods) {
        PaymentMethod cardsPaymentMethod = getPaymentMethod(paymentMethods, AdyenConstants.CARD_PAYMENT_METHOD_TYPE);
        if (cardsPaymentMethod == null) {
            throw new AuraHandledException('No card payment method type found');
        } else {
            return new List<PaymentMethod>{cardsPaymentMethod};
        }
    }

    public static PaymentMethod getPaymentMethod(List<PaymentMethod> paymentMethods, String type) {
        if (paymentMethods == null || String.isBlank(type)) {
            return null;
        }
        for (PaymentMethod paymentMethod : paymentMethods) {
            if (paymentMethod.type.equalsIgnoreCase(type)) {
                return paymentMethod;
            }
        }
        return null;
    }

    public static HttpResponse makePostRequest(String endpoint, String body) {
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:AdyenCheckout' + endpoint);
        req.setMethod('POST');
        req.setHeader('Content-Type', 'application/json');
        req.setBody(body);
        return new Http().send(req);
    }
}