adyen-appexchange/force-app/main/default/objects/LogEntry__c/LogEntry__c.object-meta.xml
<CustomObject>
    <label>Log Entry</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogEntry__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

adyen-appexchange/force-app/main/default/objects/LogEntry__c/recordTypes/Exception.recordType-meta.xml
<RecordType>
    <fullName>Exception</fullName>
    <active>true</active>
    <label>Exception</label>
</RecordType>

force-app/main/default/classes/LogEntryTest.cls
@IsTest
private class LogEntryTest {
    @IsTest
    static void insertLogExceptionTest() {
        // given
        Exception error = new AuraHandledException('error');
        String logName = 'Log Name';
        String className = 'ClassName';
        String methodName = 'MethodName';
        String message = 'message';
        String details = 'details';
        Id cartId = null;
        // when
        LogEntry.insertLogException(error, logName, className, methodName);
        LogEntry.insertLogException(error, logName, className, methodName, details);
        LogEntry.insertLogException(error, logName, className, methodName, cartId);
        LogEntry.insertLogError(logName, cartId, message, details);
        // then
        Assert.areEqual(4, [SELECT COUNT() FROM LogEntry__c WHERE Severity__c LIKE :LogEntry.SeverityLevel.ERROR.name()]);

        // given a critical exception
        error = new AdyenDropInController.CriticalException();
        // when
        LogEntry.insertLogException(error, logName, className, methodName, cartId);
        // then
        Assert.areEqual(1, [SELECT COUNT() FROM LogEntry__c WHERE Severity__c LIKE :LogEntry.SeverityLevel.CRITICAL.name()]);
    }

    @IsTest
    static void insertInformationLogTest() {
        // given
        String logName = 'Log Name';
        String message = 'message';
        String details = 'details';
        // when
        LogEntry.insertLogInformation(logName, null, message, details);
        // then
        Assert.areEqual(1, [SELECT COUNT() FROM LogEntry__c WHERE Severity__c LIKE :LogEntry.SeverityLevel.INFO.name()]);
    }
}